GET http://localhost:3000/cart-api
###
GET http://localhost:3000/user-api
### 
GET http://localhost:3000/admin-api
###
GET http://localhost:3000/orders-api
###
GET http://localhost:3000/product-api
###
GET http://localhost:3000/auth-api
###
GET http://localhost:3000/artisan-api
###
POST http://localhost:3000/user-api/user
Content-Type: application/json

{
    "name":"radha",
    "email":"radha@gmail.com",
    "password":"123",
    "role":"user",
    "phone":"9012345678",
    "address":{
        "street":"sr nagar street",
        "city":"hyderabad",
        "state":"telangana",
        "country":"india",
        "pincode":"500084"
    },
    "profileImage":""
}
###
POST http://localhost:3000/artisan-api/artisan
Content-Type: application/json

{
    "userId":"68d6a694994de9fc92ab7ee0",
    "shopName":"saree shop",
    "bio":"we make sarees",
    "craftType":"sarees",
    "location":{
        "street":"pr nagar street",
        "city":"hyderabad",
        "state":"telangana",
        "country":"india",
        "pincode":"500084"
    },
    "portfolioImages":[""],
    "isVerified":false,
    "createdAt":""
}

###
GET http://localhost:3000/artisan-api/artisans?craftType=handloom
###
GET http://localhost:3000/artisan-api/artisans/68d665824ae4f29f0d32a6ba
###
PATCH http://localhost:3000/artisan-api/artisans/68d5493894806acabc27139e
Content-Type: application/json

{
  "shopName": "Updated Artisan Shop",
  "bio": "We now make pottery and sculptures",
  "rating": 4.5,
  "verified": true
}

###
DELETE http://localhost:3000/artisan-api/artisans/68d5493894806acabc27139e
###
POST http://localhost:3000/product-api/products
Content-Type: application/json

{
    "artisanId":"68d6a6ce994de9fc92ab7ee4",
    "name":"basket",
    "description":"A beautiful handmade basket.",
    "price":999,
    "category":"art",
    "stock":100,
    "images":["image1.jpg","image2.jpg"],
    "rating":4.5,
    "isApproved":false,
    "createdAt":""
}
###
GET http://localhost:3000/product-api/products?search=pot&category=pottery&minPrice=100&maxPrice=500&page=1&limit=5
###
GET http://localhost:3000/product-api/products/68d66865d585145d74b0364d
###
PUT http://localhost:3000/product-api/products/68d66865d585145d74b0364d
Content-Type: application/json

{
    "name":"Updated Handmade Vase",
    "description":"An updated beautiful handmade vase.",
    "price":59.99,
    "category":"Home Decor",
    "stock":80,
    "images":["updated_image1.jpg","updated_image2.jpg"],
    "ratings":4.7,
    "isApproved":true
}
###
POST http://localhost:3000/cart-api/cart
Content-Type: application/json

{
    "userId":"68d7ebe722a572628362152a",
    "productId":"68d7ec4822a572628362152e",
    "quantity":2
}

###
GET http://localhost:3000/cart-api/cart/68d52e57bd582c0e1d35996f
###
PUT http://localhost:3000/cart-api/cart/68d52e57bd582c0e1d35996f/68d68b27a425b05c7fcea641
Content-Type: application/json

{
    "quantity":3
}

###
POST http://localhost:3000/orders-api/order
Content-Type: application/json

{
  "userId": "68d7ebe722a572628362152a",
    "items": [
        {
        "productId": "68d7ec4822a572628362152e",
        "quantity": 2,
        "price": 2500
        }
    ],
  "shippingAddress": {
    "street": "pr street",
    "city": "Hyderabad",
    "state": "Telangana",
    "country": "India",
    "pincode": "500084"
  }
}
###
GET http://localhost:3000/orders-api/orders
Content-Type: application/json

{
  "userId": "68d7ebe722a572628362152a"
}
###
GET http://localhost:3000/orders-api/order/68d7f10822a5726283621547
###
PUT http://localhost:3000/orders-api/order/68d7f10822a5726283621547/status
Content-Type: application/json

{
  "status": "shipped"
}
###
POST http://localhost:3000/review-api/reviews
Content-Type: application/json

{
  "userId": "68d7ebe722a572628362152a",
  "productId": "68d7ec4822a572628362152e",
  "rating": 5,
  "comment": "Excellent product! Highly recommend."
}
###
GET http://localhost:3000/review-api/reviews/68d7ec4822a572628362152e
###
GET http://localhost:3000/admin-api/users
###
GET http://localhost:3000/admin-api/users/68d6a1384122d408dd590144/ban